import { ArchWallError, IrVersionMismatchError } from "../errors.js";

/** Semver of the Project Graph IR schema itself, independent of package versions. */
export const IR_VERSION = "1.0.0";

export type ModuleId = string;

export type WellKnownCapability =
  /** `Edge.loc` is populated. */
  | "import-locations"
  /** Dynamic `import()` edges are present and marked `kind: "dynamic"`. */
  | "dynamic-imports"
  /** Every module in the project is present; absence of a module IS evidence. */
  | "complete-graph"
  /** Re-export edges are distinguished from plain imports. */
  | "reexport-edges"
  /**
   * `Edge.rawSpecifier` is what the AUTHOR WROTE, not a copy of the resolved id.
   *
   * The capability the model was missing, and the one that mattered most: under Vite dev
   * the module graph carries no specifiers, so `rawSpecifier` defaults to the resolved id
   * and every specifier-pattern rule matches nothing — reporting a clean run rather than
   * an unavailable one. A rule that reads `rawSpecifier` must require this.
   */
  | "raw-specifiers";

/**
 * Open union: adapters may declare capabilities core does not know about, and rules
 * may require them, without an IR major. `WellKnownCapability` keeps autocomplete
 * useful for the ones core ships.
 */
export type Capability = WellKnownCapability | (string & {});

export interface HostInfo {
  name: string;
  version: string;
  capabilities: ReadonlySet<Capability>;
}

export interface SourceLocation {
  file: string;
  /** 1-based */
  line: number;
  /** 0-based */
  column: number;
}

export type WellKnownEdgeKind = "static" | "dynamic" | "reexport";

/**
 * Open union so future graph facts (CSS imports, worker edges, type-only edges) arrive
 * additively. Consumers must treat an unrecognised kind as "some dependency exists" —
 * never assume exhaustiveness.
 */
export type EdgeKind = WellKnownEdgeKind | (string & {});

/**
 * What a module *is*, relative to the project being analysed. This is the distinction
 * `external: boolean` could not make: a Node builtin, a sibling workspace package, and a
 * third-party dependency are three different things to an architecture rule, and
 * collapsing them makes purity rules wrong (`node:crypto` in a domain layer is not a
 * third-party dependency).
 *
 * - `source`     — a first-party file inside the analysed project
 * - `workspace`  — a file owned by a *different* package in the same monorepo
 * - `package`    — a third-party dependency (node_modules)
 * - `builtin`    — a runtime builtin (`node:fs`, `bun:sqlite`, …)
 * - `virtual`    — generated by the toolchain; no file on disk
 * - `unresolved` — the specifier could not be resolved to anything
 * - `excluded`   — a real project file the config's `exclude` removed from analysis
 */
export type ModuleKind =
  | "source"
  | "workspace"
  | "package"
  | "builtin"
  | "virtual"
  | "unresolved"
  | "excluded";

export interface ModuleNode {
  id: ModuleId;
  /** Absolute path; null for virtual, builtin, and unresolved modules. */
  file: string | null;
  kind: ModuleKind;
  /** npm package name, for `kind: "package"`. */
  packageName?: string;
  /** Owning workspace package name, for `kind: "workspace"`. */
  workspace?: string;
  /** Filled by classification, e.g. layer → "features". */
  tags: ReadonlyMap<string, string>;
}

/**
 * Code the project owns and can change.
 *
 * `ModuleNode.external` used to be a field here, defined as `kind !== "source"`, and it
 * was wrong for two of the seven kinds. A sibling `workspace` package is first-party — but
 * `external: true` made `no-cycles` skip it, so a cycle spanning two packages of your own
 * monorepo, the most valuable cycle there is to report, was silently never reported. And
 * `excluded` is your own test file, so a rule matching `{ external: true }` matched it too.
 *
 * The lesson is that one boolean cannot express a seven-valued distinction; these
 * predicates name the two groupings that are actually meaningful, and everything else
 * should ask about `kind` directly.
 */
export const FIRST_PARTY_KINDS = ["source", "workspace"] as const satisfies readonly ModuleKind[];

/** A dependency the project does not own: third-party code or a runtime builtin. */
export const THIRD_PARTY_KINDS = ["package", "builtin"] as const satisfies readonly ModuleKind[];

export function isFirstParty(kind: ModuleKind): boolean {
  return kind === "source" || kind === "workspace";
}

export function isThirdParty(kind: ModuleKind): boolean {
  return kind === "package" || kind === "builtin";
}

export interface Edge {
  from: ModuleId;
  to: ModuleId;
  /** What the source wrote: "@/features/auth". */
  rawSpecifier: string;
  /** What it actually is after resolution. */
  resolvedPath: string;
  kind: EdgeKind;
  /** Present only if host capability allows. */
  loc?: SourceLocation;
}

export type GraphDelivery = "complete" | "progressive";

export interface ProjectGraph {
  irVersion: string;
  host: HostInfo;
  delivery: GraphDelivery;
  modules: ReadonlyMap<ModuleId, ModuleNode>;
  edges: readonly Edge[];
}

export function irMajor(version: string): number {
  const m = /^(\d+)\./.exec(version);
  if (!m) throw new ArchWallError(`Malformed IR version: "${version}"`);
  return Number(m[1]);
}

export function assertIrCompatible(graphVersion: string): void {
  if (irMajor(graphVersion) !== irMajor(IR_VERSION)) {
    throw new IrVersionMismatchError(graphVersion, IR_VERSION);
  }
}
